[package]
name = "wasmer-examples/hugo-wasmer-starter"
version = "0.2.1"
description = "Wasmer Hugo starter package"
readme = "README.md"
repository = "https://github.com/wasmer-examples/hugo-wasmer-starter"

[dependencies]
"wasmer/static-web-server" = "^1"

[fs]
public = "public"
